version: "3"
services:
  timetr4cker:
    image: timetr4cker
    restart: always
    build: ./api/
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    command: bash -c "yarn start"
    volumes:
      - ./api:/app

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/volumes/postgres-data
